# Automatically generated by configure - do not modify
SRC_PATH=/home/builder/rpmbuild/BUILD/qemu-4.2.1/roms/seabios
AS=as
CCAS=gcc
CC=gcc
BCC=bcc
CPP=gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
